/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.apu.pssdk;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class CITest {
    @Test public void someLibraryMethodReturnsTrue() {
        CI classUnderTest = new CI();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
