/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.apu.pssdk;

import org.junit.Test;
import static org.junit.Assert.*;

public class CITest {
    @Test public void someLibraryMethodReturnsTrue() {
        CI classUnderTest = new CI();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
