plugins {
    id 'java-library'
    id("com.gradleup.shadow") version "9.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'edu.apu.pssdk', name: 'pssdk', version: '4.0.0'
    implementation group: 'com.oracle.peoplesoft', name: 'psjoa', version: "$System.env.PSJOA_JAR_VERSION"
    implementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.5.18'
}
